# Generated by Django 5.1.4 on 2024-12-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="desc",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="category"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product"),
        ),
    ]
